tenant: wjklos
app: sphere
service: sphere-seed

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-2
  cfnRole: arn:aws:iam::079469020281:role/ServerlessCloudFormationRole

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/handlers/**

functions:
  addSeed:
    handler: bin/handlers/addSeed
    description: "Adds a Seed to the database."
    # package:
    #  include:
    #    - ./bin/handlers/addSeed
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CRUDSeedQ
              - Arn
  updateSeed:
    handler: bin/handlers/updateSeed
    description: "Updates a Seed to the database."
    # package:
    #  include:
    #    - ./bin/handlers/updateSeed
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CRUDSeedQ
              - Arn
  deleteSeed:
    handler: bin/handlers/deleteSeed
    description: "Deletes a Seed from the database."
    # package:
    #  include:
    #    - ./bin/handlers/deleteSeed
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CRUDSeedQ
              - Arn
  getSeed:
    handler: bin/handlers/getSeed
    description: "Retrieves a Seed from the database."
    # package:
    #  include:
    #    - ./bin/handlers/getSeed
  listSeeds:
    handler: bin/handlers/listSeeds
    description: "Lists all the specified Seeds in the database."
    # package:
    #  include:
    #    - ./bin/handlers/listSeeds
  loadSeeds:
    handler: bin/handlers/loadSeeds
    description: "Loads bulk Seeds in to the database."
    # package:
    #  include:
    #    - ./bin/handlers/loadSeeds
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - CRUDSeedQ
              - Arn
resources:
  Resources:
    CRUDSeedQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "CRUDSeedQ"
